### ISSUE TITLE
Recreate the Navbar dropdown to fit the design

### ISSUE THREAD

**Issue by techstudioconsults** [Georgeisi/workshop#4]
https://www.figma.com/file/Chbc59FiOQ0xioNMTMNBDu/WorkshopApps-(Copy)?type=design&node-id=1-472&mode=design&t=wozTibzRVjunBgKN-0

design
![Screenshot 2023-07-06 150325](https://github.com/Georgeisi/workshop/assets/122175536/101627a6-e768-429e-b4b9-8aaa9bb2cb5d)

current implementation
![Screenshot 2023-07-06 150348](https://github.com/Georgeisi/workshop/assets/122175536/a43583f4-4599-4fb8-a09d-430c58f88f98)

**Comment by gh-i19n** [comment]
this issue has been resolved
